import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-container": "var(--color-primary-container)",
        "secondary-container": "var(--color-secondary-container)",
        "secondary-fixed-dim": "#bcc7de",
        "on-secondary-fixed": "#111c2d",
        "primary": "var(--color-primary)",
        "on-tertiary-container": "#dadbdc",
        "on-surface": "var(--color-on-surface)",
        "tertiary-fixed-dim": "#c5c7c8",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "surface-container": "var(--color-surface-container)",
        "surface-bright": "var(--color-background)",
        "on-tertiary-fixed": "#191c1d",
        "on-primary-container": "var(--color-on-primary-container)",
        "on-secondary-container": "var(--color-on-secondary-container)",
        "inverse-surface": "#213145",
        "background": "var(--color-background)",
        "tertiary-container": "#5e6061",
        "surface-tint": "var(--color-primary)",
        "on-secondary": "#ffffff",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "primary-fixed": "var(--color-primary-fixed)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        "outline-variant": "var(--color-outline-variant)",
        "tertiary": "#46494a",
        "surface-dim": "var(--color-surface-container-high)",
        "outline": "var(--color-outline)",
        "surface": "var(--color-surface)",
        "tertiary-fixed": "#e1e3e4",
        "on-background": "var(--color-on-background)",
        "on-primary-fixed": "#0f0069",
        "on-error-container": "var(--color-on-error-container)",
        "on-tertiary": "#ffffff",
        "secondary-fixed": "#d8e3fb",
        "primary-fixed-dim": "var(--color-primary-fixed-dim)",
        "inverse-on-surface": "#eaf1ff",
        "surface-container-low": "var(--color-surface-container-low)",
        "on-primary-fixed-variant": "#3323cc",
        "secondary": "var(--color-secondary)",
        "error-container": "var(--color-error-container)",
        "error": "var(--color-error)",
        "on-tertiary-fixed-variant": "#454748",
        "on-error": "#ffffff",
        "inverse-primary": "var(--color-primary-fixed-dim)",
        "on-secondary-fixed-variant": "#3c475a",
        "surface-container-high": "var(--color-surface-container-high)",
        "surface-variant": "var(--color-surface-container-high)",
        "on-primary": "var(--color-on-primary)"
      },
      maxWidth: {
        sm: '24rem',
        md: '28rem',
        lg: '32rem',
        xl: '36rem',
        '2xl': '42rem',
        '3xl': '48rem',
        '4xl': '56rem',
        '5xl': '64rem',
        '6xl': '72rem',
        '7xl': '80rem',
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        sm: "8px",
        "margin-mobile": "16px",
        base: "4px",
        lg: "24px",
        md: "16px",
        "margin-desktop": "32px",
        xl: "32px",
        gutter: "16px",
        xs: "4px",
        "2xl": "48px"
      },
      fontFamily: {
        "headline-md": ["Geist"],
        "headline-lg-mobile": ["Geist"],
        "headline-lg": ["Geist"],
        "headline-sm": ["Geist"],
        "body-lg": ["Geist"],
        "body-md": ["Geist"],
        "label-md": ["Geist"],
        "body-sm": ["Geist"]
      },
      fontSize: {
        "headline-md": ["1.5rem", { lineHeight: "2rem", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-lg-mobile": ["1.5rem", { lineHeight: "2rem", fontWeight: "600" }],
        "headline-lg": ["1.875rem", { lineHeight: "2.375rem", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-sm": ["1.25rem", { lineHeight: "1.75rem", fontWeight: "600" }],
        "body-lg": ["1.125rem", { lineHeight: "1.75rem", fontWeight: "400" }],
        "body-md": ["1rem", { lineHeight: "1.5rem", fontWeight: "400" }],
        "label-md": ["0.75rem", { lineHeight: "1rem", letterSpacing: "0.02em", fontWeight: "500" }],
        "body-sm": ["0.875rem", { lineHeight: "1.25rem", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
};
export default config;